version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: college_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: college_redis
    ports:
      - "6379:6379"

  college-scraper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://go-backend:8080
    container_name: college_scraper
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_HOST=0.0.0.0
      - API_PORT=8501
      - BACKEND_URL=http://go-backend:8080
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
