"""
mock_server/data.py
===================
Static source data for the top-20 Indian engineering colleges.
The mock HTTP server renders this into HTML pages that the Scrapy spider
can parse – identical workflow to scraping real sites, just local.
"""
from __future__ import annotations

COLLEGES: list[dict] = [
    {
        "slug":    "iit-madras",
        "name":    "Indian Institute of Technology Madras",
        "short":   "IIT Madras",
        "location":"Chennai, Tamil Nadu, India",
        "nirf":    1,
        "qs":      "285",
        "the":     "251-300",
        "established": "1959",
        "campus":  "617 acres",
        "total_students": 9_812,
        "faculty": 625,
        "intl":    380,
        "ug_min":  118_300, "ug_max":  239_200,
        "pg_min":   38_600, "pg_max":  118_400,
        "male_pct": 78,
        "avg_ctc": "₹21.8 LPA",
        "high_ctc":"₹3.67 Cr (International)",
        "low_ctc": "₹8.5 LPA",
        "labs":    "120+",
        "website": "https://www.iitm.ac.in",
        "about": (
            "IIT Madras, established in 1959 with assistance from the West German government, "
            "is consistently ranked as India's top engineering institution. Located in a 617-acre "
            "campus within a forest reserve in Chennai, it houses over 550 faculty, "
            "8,000+ students, and research centres of global repute. "
            "It has been ranked #1 in NIRF (Engineering) every year since 2018 and "
            "features in the QS World Rankings 201-300."
        ),
        "departments": [
            "Aerospace Engineering","Applied Mechanics","Biotechnology",
            "Chemical Engineering","Chemistry","Civil Engineering",
            "Computer Science & Engineering","Electrical Engineering",
            "Engineering Design","Humanities & Social Sciences",
            "Management Studies","Mathematics","Mechanical Engineering",
            "Metallurgical & Materials Engineering","Ocean Engineering",
            "Physics","Engineering Physics",
        ],
        "ug_programs": [
            "B.Tech Aerospace Engineering","B.Tech Chemical Engineering",
            "B.Tech Civil Engineering","B.Tech Computer Science & Engineering",
            "B.Tech Electrical Engineering","B.Tech Engineering Design",
            "B.Tech Mechanical Engineering","B.Tech Metallurgical Engineering",
            "B.Tech Naval Architecture","B.Tech Ocean Engineering",
            "B.Sc Engineering Physics","B.Sc Mathematics","B.Sc Chemistry",
            "B.Sc Physics","B.A Humanities & Social Sciences",
            "B.Tech Biotechnology","B.Tech Applied Mechanics",
        ],
        "pg_programs": [
            "M.Tech Computer Science","M.Tech Electrical Engineering",
            "M.Tech Mechanical Engineering","M.Tech Civil Engineering",
            "M.Tech Aerospace Engineering","M.Tech Chemical Engineering",
            "M.Tech Ocean Engineering","M.Tech Nano Science & Technology",
            "M.Sc Mathematics","M.Sc Physics","M.Sc Chemistry",
            "MBA (EMBA)","M.Tech Biomedical Engineering","M.Tech Data Science",
        ],
        "phd_programs": [
            "PhD Computer Science","PhD Electrical Engineering",
            "PhD Mechanical Engineering","PhD Mathematics","PhD Physics",
            "PhD Chemistry","PhD Chemical Engineering","PhD Biotechnology",
            "PhD Aerospace Engineering","PhD Ocean Engineering",
            "PhD Climate Science","PhD Materials Science",
        ],
        "scholarships": [
            "IITM Merit cum Means Scholarship (full tuition)",
            "Institute Free Studentship (SC/ST)",
            "National Fellowship for SC/ST (UGC)",
            "Prime Minister's Special Scholarship",
            "Defence Research Fellowship",
            "Industry-sponsored Research Scholarship",
            "International Collaboration Scholarship",
        ],
    },
    {
        "slug":    "iit-bombay",
        "name":    "Indian Institute of Technology Bombay",
        "short":   "IIT Bombay",
        "location":"Mumbai, Maharashtra, India",
        "nirf":    2,
        "qs":      "118",
        "the":     "201-250",
        "established": "1958",
        "campus":  "550 acres",
        "total_students": 10_519,
        "faculty": 678,
        "intl":    425,
        "ug_min":  119_950, "ug_max":  248_750,
        "pg_min":   45_000, "pg_max":  120_000,
        "male_pct": 79,
        "avg_ctc": "₹26.35 LPA",
        "high_ctc":"₹3.67 Cr (International)",
        "low_ctc": "₹9 LPA",
        "labs":    "115+",
        "website": "https://www.iitb.ac.in",
        "about": (
            "IIT Bombay, founded in 1958 with Soviet assistance, is one of India's most "
            "prestigious engineering institutions and is located on the Powai lake campus "
            "in Mumbai. It houses 17 academic departments, 4 schools, and over 2 research parks. "
            "IIT Bombay is ranked #118 globally by QS and is known for stellar placement "
            "records and vibrant startup culture with numerous unicorn alumni companies."
        ),
        "departments": [
            "Aerospace Engineering","Chemical Engineering","Chemistry",
            "Civil Engineering","Computer Science & Engineering","Earth Sciences",
            "Electrical Engineering","Energy Science & Engineering",
            "Humanities & Social Sciences","Industrial Design Centre",
            "Mathematics","Mechanical Engineering",
            "Metallurgical Engineering & Materials Science","Physics",
            "Systems & Control Engineering","Biosciences & Bioengineering",
        ],
        "ug_programs": [
            "B.Tech Aerospace Engineering","B.Tech Chemical Engineering",
            "B.Tech Civil Engineering","B.Tech Computer Science & Engineering",
            "B.Tech Electrical Engineering","B.Tech Mechanical Engineering",
            "B.Tech Engineering Physics","B.Tech Metallurgical Engineering",
            "B.Tech Energy Science & Engineering","B.Sc Chemistry",
            "B.Sc Mathematics","B.Sc Physics","B.Tech Biosciences",
            "B.Tech Systems & Control","B.Des Industrial Design",
            "B.Tech Earth Sciences",
        ],
        "pg_programs": [
            "M.Tech Computer Science","M.Tech Electrical Engineering",
            "M.Tech Mechanical Engineering","M.Tech Aerospace Engineering",
            "M.Tech Chemical Engineering","M.Tech Systems & Control",
            "M.Sc Mathematics","M.Sc Physics","M.Sc Chemistry",
            "MBA (SJMSOM)","M.Tech Industrial Design","M.Tech Energy Science",
            "M.Tech Geoinformatics","M.Tech Structural Engineering",
        ],
        "phd_programs": [
            "PhD Computer Science","PhD Electrical Engineering",
            "PhD Mechanical Engineering","PhD Mathematics","PhD Physics",
            "PhD Chemistry","PhD Chemical Engineering","PhD Biosciences",
            "PhD Aerospace Engineering","PhD Earth Sciences",
            "PhD Industrial Design","PhD Materials Science",
        ],
        "scholarships": [
            "IITB Merit cum Means Scholarship",
            "Institute Free Studentship (SC/ST/PH)",
            "National Scholarship for Higher Education",
            "Aditya Birla Scholarship",
            "Reliance Industries Scholarship",
            "Prime Minister Research Fellowship (PhD)",
            "International Student Scholarship",
        ],
    },
    {
        "slug":    "iit-delhi",
        "name":    "Indian Institute of Technology Delhi",
        "short":   "IIT Delhi",
        "location":"New Delhi, Delhi, India",
        "nirf":    3,
        "qs":      "197",
        "the":     "251-300",
        "established": "1961",
        "campus":  "325 acres",
        "total_students": 8_724,
        "faculty": 592,
        "intl":    360,
        "ug_min":  105_700, "ug_max":  245_000,
        "pg_min":   40_000, "pg_max":  115_000,
        "male_pct": 80,
        "avg_ctc": "₹24.5 LPA",
        "high_ctc":"₹2.1 Cr",
        "low_ctc": "₹9 LPA",
        "labs":    "105+",
        "website": "https://home.iitd.ac.in",
        "about": (
            "IIT Delhi was established in 1961 and granted the status of an 'Institute of National "
            "Importance' by an Act of Parliament in 1963. Situated in New Delhi on a 325-acre campus, "
            "it has 13 departments and 4 interdisciplinary centres. "
            "IITD is ranked #197 by QS World University Rankings 2025 and is known for its vibrant "
            "research ecosystem, robust international collaborations, and exceptional placement records."
        ),
        "departments": [
            "Applied Mechanics","Biochemical Engineering & Biotechnology",
            "Chemical Engineering","Chemistry","Civil Engineering",
            "Computer Science & Engineering","Electrical Engineering",
            "Humanities & Social Sciences","Management Studies",
            "Mathematics","Mechanical Engineering",
            "Physics","Textile & Fibre Engineering",
        ],
        "ug_programs": [
            "B.Tech Computer Science & Engineering",
            "B.Tech Electrical Engineering","B.Tech Mechanical Engineering",
            "B.Tech Civil Engineering","B.Tech Chemical Engineering",
            "B.Tech Textile Technology","B.Tech Production & Industrial Engineering",
            "B.Tech Engineering Physics","B.Tech Biochemical Engineering",
            "B.Sc Mathematics","B.Sc Physics","B.Sc Chemistry",
            "B.Tech Polymer Science & Technology","B.A Humanities",
            "B.Tech Mathematics & Computing","B.Tech Materials Engineering",
        ],
        "pg_programs": [
            "M.Tech Computer Science","M.Tech VLSI Design",
            "M.Tech Power Systems","M.Tech Structural Engineering",
            "M.Tech Manufacturing Engineering","M.Tech Biotechnology",
            "M.Sc Physics","M.Sc Chemistry","M.Sc Mathematics",
            "MBA (DMS)","M.Tech Polymer Science","M.Tech Geomatics",
            "M.Tech Textile Engineering","M.Tech Instrumentation",
        ],
        "phd_programs": [
            "PhD Computer Science","PhD Electrical Engineering",
            "PhD Mechanical Engineering","PhD Civil Engineering",
            "PhD Chemical Engineering","PhD Physics","PhD Chemistry",
            "PhD Mathematics","PhD Biotechnology","PhD Management Studies",
            "PhD Humanities & Social Sciences","PhD Textile Engineering",
        ],
        "scholarships": [
            "IITD Merit cum Means Scholarship",
            "SC/ST Free Studentship",
            "OBC Non-Creamy Layer Scholarship",
            "INSPIRE Fellowship (DST)",
            "Prime Minister Research Fellowship",
            "CSIR Junior Research Fellowship",
            "Industry PhD Fellowship (TCS, Infosys)",
        ],
    },
    {
        "slug":    "iit-kanpur",
        "name":    "Indian Institute of Technology Kanpur",
        "short":   "IIT Kanpur",
        "location":"Kanpur, Uttar Pradesh, India",
        "nirf":    4,
        "qs":      "278",
        "the":     "301-350",
        "established": "1959",
        "campus":  "1055 acres",
        "total_students": 8_125,
        "faculty": 520,
        "intl":    295,
        "ug_min":  110_250, "ug_max":  235_000,
        "pg_min":   38_000, "pg_max":  110_000,
        "male_pct": 81,
        "avg_ctc": "₹23.5 LPA",
        "high_ctc":"₹2.32 Cr",
        "low_ctc": "₹8.5 LPA",
        "labs":    "100+",
        "website": "https://www.iitk.ac.in",
        "about": (
            "IIT Kanpur (IITK) was established in 1959 and was the first institution in India "
            "to offer an education in computer science and engineering in 1963. "
            "Set on a sprawling 1055-acre campus in Kanpur, Uttar Pradesh, IITK is renowned "
            "for pioneering research in space science, cyber security, and clean energy. "
            "It maintains active collaborations with MIT, Caltech, and leading global institutions."
        ),
        "departments": [
            "Aerospace Engineering","Biological Sciences & Bioengineering",
            "Chemical Engineering","Chemistry","Civil Engineering",
            "Computer Science & Engineering","Earth Sciences",
            "Electrical Engineering","Humanities & Social Sciences",
            "Industrial & Management Engineering","Materials Science & Engineering",
            "Mathematics & Statistics","Mechanical Engineering","Physics",
        ],
        "ug_programs": [
            "B.Tech Computer Science & Engineering",
            "B.Tech Electrical Engineering","B.Tech Mechanical Engineering",
            "B.Tech Aerospace Engineering","B.Tech Chemical Engineering",
            "B.Tech Civil Engineering","B.Tech Materials Science",
            "B.Tech Earth Sciences","B.Sc Mathematics & Statistics",
            "B.Sc Physics","B.Sc Chemistry","B.Sc Biological Sciences",
            "B.Tech Industrial Engineering","B.Tech Economic Sciences",
            "B.Des Industrial Design","B.Tech Photonics",
        ],
        "pg_programs": [
            "M.Tech Computer Science","M.Tech Electrical Engineering",
            "M.Tech Mechanical Engineering","M.Tech Aerospace Engineering",
            "M.Tech Materials Science","M.Tech Nuclear Engineering",
            "M.Sc Mathematics","M.Sc Physics","M.Sc Chemistry",
            "MBA","M.Tech Industrial Engineering","M.Tech Earth Sciences",
            "M.Tech Environment Engineering","M.Tech Laser Technology",
        ],
        "phd_programs": [
            "PhD Computer Science","PhD Electrical Engineering",
            "PhD Mechanical Engineering","PhD Mathematics",
            "PhD Physics","PhD Chemistry","PhD Chemical Engineering",
            "PhD Aerospace Engineering","PhD Materials Science",
            "PhD Earth Sciences","PhD Biological Sciences","PhD Management",
        ],
        "scholarships": [
            "IITK Merit cum Means Scholarship",
            "SC/ST & OBC Free Studentship",
            "Department of Science & Technology Fellowship",
            "Sanjoy Mitter Scholarship",
            "Sri G.D. Birla Award for Scientific Research",
            "Prime Minister Research Fellowship",
            "Industrial Research & Development Scholarship",
        ],
    },
    {
        "slug":    "iit-roorkee",
        "name":    "Indian Institute of Technology Roorkee",
        "short":   "IIT Roorkee",
        "location":"Roorkee, Uttarakhand, India",
        "nirf":    5,
        "qs":      "369",
        "the":     "351-400",
        "established": "1847",
        "campus":  "365 acres",
        "total_students": 11_248,
        "faculty": 582,
        "intl":    315,
        "ug_min":  105_700, "ug_max":  235_000,
        "pg_min":   38_000, "pg_max":  108_000,
        "male_pct": 77,
        "avg_ctc": "₹20.3 LPA",
        "high_ctc":"₹1.98 Cr",
        "low_ctc": "₹8.5 LPA",
        "labs":    "90+",
        "website": "https://www.iitr.ac.in",
        "about": (
            "IIT Roorkee is India's oldest technical institution, founded in 1847 as the Thomason "
            "College of Civil Engineering. It became an IIT in 2001 and is located in Roorkee, "
            "Uttarakhand. With 22 departments and 28 academic centres, IITR excels in civil/structural "
            "engineering, earthquake engineering, and water resources. "
            "It is ranked 5th by NIRF and 369th by QS 2025."
        ),
        "departments": [
            "Architecture & Planning","Biotechnology","Chemical Engineering",
            "Chemistry","Civil Engineering","Computer Science & Engineering",
            "Earth Sciences","Electrical Engineering",
            "Electronics & Communication Engineering",
            "Humanities & Social Sciences","Hydrology",
            "Management Studies","Mathematics","Mechanical & Industrial Engineering",
            "Metallurgical & Materials Engineering","Paper Technology","Physics",
            "Polymer & Process Engineering","Water Resources Development & Management",
        ],
        "ug_programs": [
            "B.Tech Computer Science & Engineering",
            "B.Tech Electrical Engineering",
            "B.Tech Electronics & Communication Engineering",
            "B.Tech Mechanical Engineering","B.Tech Civil Engineering",
            "B.Tech Chemical Engineering","B.Tech Metallurgical Engineering",
            "B.Tech Biotechnology","B.Tech Production & Industrial Engineering",
            "B.Tech Earthquake Engineering","B.Tech Geophysics",
            "B.Arch Architecture","B.Tech Paper Technology",
            "B.Sc Mathematics","B.Sc Physics","B.Sc Chemistry",
        ],
        "pg_programs": [
            "M.Tech Computer Science","M.Tech VLSI Design",
            "M.Tech Structural Engineering","M.Tech Hydrology",
            "M.Tech Environmental Engineering","M.Tech Machine Design",
            "M.Tech Biotechnology","M.Tech Power Electronics",
            "M.Sc Mathematics","M.Sc Physics","M.Sc Chemistry",
            "MBA (DMS Roorkee)","M.Tech Software Engineering",
            "M.Tech Earthquake Engineering",
        ],
        "phd_programs": [
            "PhD Computer Science","PhD Electrical Engineering",
            "PhD Civil Engineering","PhD Mechanical Engineering",
            "PhD Chemistry","PhD Physics","PhD Mathematics",
            "PhD Biotechnology","PhD Earth Sciences",
            "PhD Hydrology","PhD Management","PhD Architecture",
        ],
        "scholarships": [
            "IITR Merit cum Means Scholarship",
            "SC/ST Full Fee Waiver",
            "OBC Non-Creamy Layer 2/3rd Fee Waiver",
            "MHRD Research Fellowship",
            "Ministry of Water Resources Fellowship (Water Resources)",
            "National Fellowship for ST Students",
            "Prime Minister Research Fellowship",
        ],
    },
]

# Remaining 15 colleges with condensed data
_EXTRA_COLLEGES = [
    ("iit-kharagpur",  "Indian Institute of Technology Kharagpur",  "IIT Kharagpur",   "Kharagpur, West Bengal, India",    6, "271", "201-250", "1951", "2100 acres", 14_600, 750, 490),
    ("iit-guwahati",   "Indian Institute of Technology Guwahati",   "IIT Guwahati",    "Guwahati, Assam, India",           7, "364", "401-500", "1994", "704 acres",  7_200,  380, 220),
    ("iit-hyderabad",  "Indian Institute of Technology Hyderabad",  "IIT Hyderabad",   "Hyderabad, Telangana, India",      8, "383", "401-500", "2008", "576 acres",  4_815,  302, 180),
    ("nit-trichy",     "National Institute of Technology Tiruchirappalli", "NIT Trichy","Tiruchirappalli, Tamil Nadu, India", 9,"601-650","601-800","1964","800 acres",9_523,  454, 160),
    ("bits-pilani",    "Birla Institute of Technology and Science Pilani", "BITS Pilani","Pilani, Rajasthan, India",        10,"383", "501-600", "1964", "328 acres", 14_082, 682, 510),
    ("jadavpur",       "Jadavpur University",                        "Jadavpur University","Kolkata, West Bengal, India",   11,"701-750","601-800","1906","90 acres",  7_832,  462, 105),
    ("vit-vellore",    "Vellore Institute of Technology",            "VIT Vellore",     "Vellore, Tamil Nadu, India",       12,"801-1000","1001+","1984","372 acres", 40_000, 2_812, 620),
    ("anna-university","Anna University",                            "Anna University", "Chennai, Tamil Nadu, India",       13,"801-1000","1001+","1978","185 acres", 85_000, 5_250, 290),
    ("dtu-delhi",      "Delhi Technological University",             "DTU Delhi",       "New Delhi, Delhi, India",          14,"801-1000","1001+","1941","164 acres",  8_512,  424, 175),
    ("amrita",         "Amrita Vishwa Vidyapeetham",                 "Amrita University","Coimbatore, Tamil Nadu, India",   15,"801-1000","1001+","1994","400 acres", 18_500, 1_400, 320),
    ("nit-karnataka",  "National Institute of Technology Karnataka", "NIT Karnataka",   "Surathkal, Karnataka, India",      16,"651-700","1001+","1960","296 acres",  8_224,  384, 120),
    ("psg-tech",       "PSG College of Technology",                  "PSG Tech",        "Coimbatore, Tamil Nadu, India",    17,"1001+","1001+","1951","50 acres",    6_524,  382,  45),
    ("mit-manipal",    "Manipal Institute of Technology",            "MIT Manipal",     "Manipal, Karnataka, India",        18,"1001+","1001+","1957","188 acres",  15_120,  752, 380),
    ("srm-university", "SRM Institute of Science and Technology",   "SRM University",  "Kattankulathur, Tamil Nadu, India",19,"1001+","1001+","1985","258 acres",  52_000, 3_600, 560),
    ("pec-chandigarh", "Punjab Engineering College",                 "PEC Chandigarh",  "Chandigarh, Punjab, India",        20,"1001+","1001+","1921","263 acres",   4_156,  252,  28),
    # 30 additional colleges to reach 51 total
    ("nit-warangal",   "National Institute of Technology Warangal",  "NIT Warangal",    "Warangal, Telangana, India",        21,"651-700","801-1000","1959","248 acres",  7_200,  390, 110),
    ("nit-calicut",    "National Institute of Technology Calicut",   "NIT Calicut",     "Calicut, Kerala, India",            22,"651-700","801-1000","1961","120 acres",  6_500,  350,  80),
    ("nit-rourkela",   "National Institute of Technology Rourkela",  "NIT Rourkela",    "Rourkela, Odisha, India",           23,"651-700","1001+","1961","676 acres",   8_000,  421, 130),
    ("vnit-nagpur",    "Visvesvaraya National Institute of Technology","VNIT Nagpur",    "Nagpur, Maharashtra, India",        24,"701-750","1001+","1960","208 acres",   6_800,  348,  75),
    ("iiit-hyderabad", "International Institute of Information Technology Hyderabad","IIIT Hyderabad","Hyderabad, Telangana, India",25,"801-1000","1001+","1998","66 acres",2_400, 145,  95),
    ("iit-indore",     "Indian Institute of Technology Indore",      "IIT Indore",      "Indore, Madhya Pradesh, India",     26,"501-510","601-800","2009","501 acres",  3_400,  210,  60),
    ("iit-patna",      "Indian Institute of Technology Patna",       "IIT Patna",       "Patna, Bihar, India",               28,"651-700","801-1000","2008","501 acres",  2_800,  178,  45),
    ("iit-gandhinagar","Indian Institute of Technology Gandhinagar", "IIT Gandhinagar", "Gandhinagar, Gujarat, India",       27,"651-700","801-1000","2008","400 acres",  2_600,  170,  55),
    ("iit-jodhpur",    "Indian Institute of Technology Jodhpur",     "IIT Jodhpur",     "Jodhpur, Rajasthan, India",         29,"701-750","1001+","2008","852 acres",   2_500,  165,  40),
    ("iit-mandi",      "Indian Institute of Technology Mandi",       "IIT Mandi",       "Mandi, Himachal Pradesh, India",   30,"701-750","1001+","2009","527 acres",   2_100,  148,  35),
    ("thapar",         "Thapar Institute of Engineering and Technology","Thapar University","Patiala, Punjab, India",         31,"1001+","1001+","1956","250 acres",  12_500,  620, 180),
    ("coep",           "College of Engineering Pune",                "COEP Pune",       "Pune, Maharashtra, India",          32,"1001+","1001+","1854","47 acres",    6_200,  340,  55),
    ("rvce",           "RV College of Engineering",                  "RVCE Bangalore",  "Bengaluru, Karnataka, India",       33,"1001+","1001+","1963","16 acres",    7_400,  396,  70),
    ("bms-engineering","BMS College of Engineering",                 "BMS College",     "Bengaluru, Karnataka, India",       34,"1001+","1001+","1946","22 acres",    5_800,  320,  48),
    ("kiit",           "Kalinga Institute of Industrial Technology", "KIIT University", "Bhubaneswar, Odisha, India",        35,"801-1000","1001+","1992","25 sq km", 30_000, 1_850, 490),
    ("sastra",         "SASTRA Deemed University",                   "SASTRA University","Thanjavur, Tamil Nadu, India",     36,"1001+","1001+","1984","250 acres",  12_000,  682,  80),
    ("pes-university", "PES University",                             "PES University",  "Bengaluru, Karnataka, India",       37,"1001+","1001+","1988","25 acres",    8_200,  430,  95),
    ("mnnit-allahabad","Motilal Nehru National Institute of Technology","MNNIT Allahabad","Allahabad, Uttar Pradesh, India",  38,"1001+","1001+","1961","222 acres",   6_500,  332,  72),
    ("nit-silchar",    "National Institute of Technology Silchar",   "NIT Silchar",     "Silchar, Assam, India",             39,"1001+","1001+","1967","625 acres",   5_800,  298,  55),
    ("chandigarh-univ","Chandigarh University",                      "CU Chandigarh",   "Mohali, Punjab, India",             40,"1001+","1001+","2012","200 acres",  35_000, 2_200, 720),
    ("lpu",            "Lovely Professional University",             "LPU",             "Phagwara, Punjab, India",           41,"1001+","1001+","2005","600 acres",  35_000, 3_500, 840),
    ("sathyabama",     "Sathyabama Institute of Science and Technology","Sathyabama University","Chennai, Tamil Nadu, India", 42,"1001+","1001+","1987","165 acres", 15_500, 1_040,  90),
    ("jaypee-it",      "Jaypee Institute of Information Technology", "JIIT Noida",      "Noida, Uttar Pradesh, India",       43,"1001+","1001+","2001","68 acres",   6_800,  385,  55),
    ("amity",          "Amity University",                           "Amity University","Noida, Uttar Pradesh, India",       44,"1001+","1001+","2005","150 acres", 50_000, 3_200, 1200),
    ("vit-bhopal",     "VIT Bhopal University",                      "VIT Bhopal",      "Bhopal, Madhya Pradesh, India",     45,"1001+","1001+","2017","300 acres",  8_000,  420,  55),
    ("graphic-era",    "Graphic Era University",                     "Graphic Era",     "Dehradun, Uttarakhand, India",      46,"1001+","1001+","1993","25 acres",  12_000,  680,  75),
    ("iit-bhubaneswar","Indian Institute of Technology Bhubaneswar", "IIT Bhubaneswar", "Bhubaneswar, Odisha, India",        47,"851-900","1001+","2008","936 acres",  2_800,  175,  42),
    ("nit-durgapur",   "National Institute of Technology Durgapur",  "NIT Durgapur",    "Durgapur, West Bengal, India",      48,"1001+","1001+","1960","213 acres",   5_600,  290,  62),
    ("lnm-iit",        "LNM Institute of Information Technology",    "LNMIIT Jaipur",   "Jaipur, Rajasthan, India",          49,"1001+","1001+","2002","100 acres",   3_200,  185,  38),
    ("symbiosis-tech", "Symbiosis Institute of Technology",          "SIT Pune",        "Pune, Maharashtra, India",          50,"1001+","1001+","2008","50 acres",   5_400,  310,  120),
]

for (slug, name, short, location, nirf, qs, the, est, campus,
     total_students, faculty, intl) in _EXTRA_COLLEGES:
    is_iit = "iit" in slug
    COLLEGES.append({
        "slug": slug, "name": name, "short": short, "location": location,
        "nirf": nirf, "qs": qs, "the": the, "established": est,
        "campus": campus, "total_students": total_students,
        "faculty": faculty, "intl": intl,
        "ug_min": 105_700 if is_iit else 50_000,
        "ug_max": 245_000 if is_iit else 350_000,
        "pg_min": 38_000  if is_iit else 40_000,
        "pg_max": 115_000 if is_iit else 250_000,
        "male_pct": 78 if is_iit else 62,
        "avg_ctc": "₹20 LPA" if is_iit else "₹10 LPA",
        "high_ctc": "₹1.8 Cr" if is_iit else "₹45 LPA",
        "low_ctc": "₹8 LPA" if is_iit else "₹5.5 LPA",
        "labs": "90+" if is_iit else "60+",
        "website": f"https://www.{slug.replace('-','')}.ac.in",
        "about": (
            f"{name}, established in {est}, is a premier engineering institution in India "
            f"located in {location}. It is ranked {nirf} in NIRF Engineering 2024 "
            f"and {qs} in QS World University Rankings 2025."
        ),
        "departments": [
            "Computer Science & Engineering","Electronics & Communication Engineering",
            "Mechanical Engineering","Civil Engineering","Electrical Engineering",
            "Chemical Engineering","Aerospace Engineering","Biotechnology",
            "Physics","Chemistry","Mathematics","Business Administration",
            "Economics","Environmental Science",
        ],
        "ug_programs": [
            "B.Tech Computer Science & Engineering",
            "B.Tech Electronics & Communication Engineering",
            "B.Tech Mechanical Engineering","B.Tech Civil Engineering",
            "B.Tech Electrical Engineering","B.Tech Chemical Engineering",
            "B.Tech Biotechnology","B.Sc Physics","B.Sc Chemistry",
            "B.Sc Mathematics","B.A Economics","B.A Business Administration",
            "B.Sc Data Science","B.Tech Production Engineering",
            "B.Tech Material Science","B.Tech Aerospace Engineering",
        ],
        "pg_programs": [
            "M.Tech Computer Science","M.Tech Electronics & Communication",
            "M.Tech Mechanical Engineering","M.Tech Civil Engineering",
            "M.Tech Electrical Engineering","M.Tech Biotechnology",
            "MBA","M.Sc Physics","M.Sc Chemistry","M.Sc Mathematics",
            "M.A Economics","M.Phil Research","M.E Software Engineering",
        ],
        "phd_programs": [
            "PhD Computer Science","PhD Physics","PhD Chemistry",
            "PhD Mathematics","PhD Mechanical Engineering",
            "PhD Electrical Engineering","PhD Biotechnology",
            "PhD Materials Science","PhD Environmental Science",
        ],
        "scholarships": [
            "Merit-based Scholarship (50-75% tuition)",
            "Need-based Financial Aid",
            "Government Scholarship (SC/ST/OBC)",
            "International Student Scholarship",
            "Sports Excellence Scholarship",
            "Research Scholarship for PhD",
            "Institute Free Studentship",
        ],
    })
# ── KPRIET (standalone entry – not part of the _EXTRA_COLLEGES loop) ─────────
COLLEGES.append({
    "slug":    "kpriet",
    "name":    "KPR Institute of Engineering and Technology",
    "short":   "KPRIET",
    "location":"Coimbatore, Tamil Nadu, India",
    "nirf":    "N/A",
    "qs":      "N/A",
    "the":     "N/A",
    "established": "2006",
    "campus":  "165 acres",
    "total_students": 6_842,
    "faculty": 412,
    "intl":    38,
    "ug_min":  75_000, "ug_max": 140_000,
    "pg_min":  55_000, "pg_max": 100_000,
    "male_pct": 56,
    "avg_ctc": "₹5.2 LPA",
    "high_ctc": "₹28 LPA",
    "low_ctc": "₹3.2 LPA",
    "labs":    "48+",
    "website": "https://www.kpriet.ac.in",
    "about": (
        "KPR Institute of Engineering and Technology (KPRIET), established in 2006, "
        "is an autonomous engineering college affiliated to Anna University, located "
        "in Coimbatore, Tamil Nadu. Spread across 165 acres of lush green campus, "
        "KPRIET is accredited by NAAC with 'A' grade and holds NBA accreditation for "
        "multiple programmes. It consistently ranks among the top private engineering "
        "colleges in Tamil Nadu, with a strong industry-academia interface, active "
        "placement cell, and over 412 experienced faculty members across 12 departments."
    ),
    "departments": [
        "Computer Science & Engineering",
        "Information Technology",
        "Electronics & Communication Engineering",
        "Electrical & Electronics Engineering",
        "Mechanical Engineering",
        "Civil Engineering",
        "Aeronautical Engineering",
        "Artificial Intelligence & Data Science",
        "Computer Science & Business Systems",
        "Mathematics",
        "Physics",
        "Chemistry",
    ],
    "ug_programs": [
        "B.E Computer Science & Engineering",
        "B.E Electronics & Communication Engineering",
        "B.E Electrical & Electronics Engineering",
        "B.E Mechanical Engineering",
        "B.E Civil Engineering",
        "B.Tech Information Technology",
        "B.E Aeronautical Engineering",
        "B.Tech Artificial Intelligence & Data Science",
        "B.Tech Computer Science & Business Systems",
        "B.Tech Cyber Security",
        "B.E Agricultural Engineering",
        "B.Tech Internet of Things",
        "B.Tech Robotics & Automation",
        "B.E Chemical Engineering",
        "B.Tech Biomedical Engineering",
        "B.Tech Food Technology",
    ],
    "pg_programs": [
        "M.E Computer Science & Engineering",
        "M.E VLSI Design",
        "M.E Power Electronics & Drives",
        "M.E Engineering Design",
        "M.E Structural Engineering",
        "M.Tech Computer Integrated Manufacturing",
        "M.Tech Information Technology",
        "MBA (Master of Business Administration)",
        "M.Sc Applied Mathematics",
        "M.Sc Computer Science",
        "M.E Communication Systems",
        "M.E Embedded System Technologies",
    ],
    "phd_programs": [
        "PhD Computer Science & Engineering",
        "PhD Electronics & Communication Engineering",
        "PhD Mechanical Engineering",
        "PhD Electrical Engineering",
        "PhD Civil Engineering",
        "PhD Mathematics",
        "PhD Physics",
        "PhD Chemistry",
        "PhD Management Studies",
    ],
    "scholarships": [
        "KPR Merit Scholarship (up to 100% tuition for rank holders)",
        "Government of Tamil Nadu SC/ST Fee Concession",
        "BC/MBC Chief Minister's Scholarship",
        "First-Generation Graduate Scholarship",
        "Sports Achievement Scholarship",
        "Anna University Merit Scholarship",
        "Industry-sponsored Scholarship (TCS, Wipro, Infosys)",
    ],
})